title = "all code is propaganda"
baseURL = "https://samnaser.com"
theme = "zaftra"
defaultContentLanguage = "en"
languageCode = "en-us"
enableEmoji = true
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
    resume = "/documents/samuel_naser_resume.pdf"
    github = "https://github.com/Monkeyanator"
    linkedin = "https://linkedin.com/in/samuel-naser/"
